version: "3"

services:
  shorturl:
    image: reg.stw.tw/go-shorturl
    restart: always
    ports:
      - "46000:3000"
    environment:
      - ENABLE_BASIC_AUTH
      - AUTH_USER
      - AUTH_PASS
      - REDIS_URL=redis:6379
      - PORT
      - REDIS_USERNAME
      - REDIS_PASSWORD
      - REDIS_DB
    networks: ["go-shorturl"]
    depends_on:
      - redis
  redis:
    image: redis
    restart: always
    networks: ["go-shorturl"]
    volumes:
      - "/mnt/data/shorturl-redis:/data"

networks:
  go-shorturl:
